<?php

class testRetornoVerificaNumero extends PHPUnit_Framework_TestCase {

    /**
     * @dataProvider provider
     */
    public function testVerificaNumeroReturn($number,$expectedReturn) {
        include 'desafio.php';
        $this->assertEquals($expectedReturn, verificaNumero($number));
    }

    public function provider()
    {
        return array(
            array(1, '1'),
            array(2, '2'),
            array(3, 'BHUR'),
            array(4, '4'),
            array(5, 'IT'),
            array(6, 'BHUR'),
            array(7, '7'),
            array(8, '8'),
            array(9, 'BHUR'),
            array(10, 'IT'),
            array(11, '11'),
            array(12, 'BHUR'),
            array(13, '13'),
            array(14, '14'),
            array(15, 'BHUR TI'),
            array(16, '16'),
            array(17, '17'),
            array(18, 'BHUR'),
            array(19, '19'),
            array(20, 'IT'),
            array(21, 'BHUR'),
            array(22, '22'),
            array(23, '23'),
            array(24, 'BHUR'),
            array(25, 'IT'),
            array(26, '26'),
            array(27, 'BHUR'),
            array(28, '28'),
            array(29, '29'),
            array(30, 'BHUR TI'),
            array(31, '31'),
            array(32, '32'),
            array(33, 'BHUR'),
            array(34, '34'),
            array(35, 'IT'),
            array(36, 'BHUR'),
            array(37, '37'),
            array(38, '38'),
            array(39, 'BHUR'),
            array(40, 'IT'),
            array(41, '41'),
            array(42, 'BHUR'),
            array(43, '43'),
            array(44, '44'),
            array(45, 'BHUR TI'),
            array(46, '46'),
            array(47, '47'),
            array(48, 'BHUR'),
            array(49, '49'),
            array(50, 'IT'),
            array(51, 'BHUR'),
            array(52, '52'),
            array(53, '53'),
            array(54, 'BHUR'),
            array(55, 'IT'),
            array(56, '56'),
            array(57, 'BHUR'),
            array(58, '58'),
            array(59, '59'),
            array(60, 'BHUR TI'),
            array(61, '61'),
            array(62, '62'),
            array(63, 'BHUR'),
            array(64, '64'),
            array(65, 'IT'),
            array(66, 'BHUR'),
            array(67, '67'),
            array(68, '68'),
            array(69, 'BHUR'),
            array(70, 'IT'),
            array(71, '71'),
            array(72, 'BHUR'),
            array(73, '73'),
            array(74, '74'),
            array(75, 'BHUR TI'),
            array(76, '76'),
            array(77, '77'),
            array(78, 'BHUR'),
            array(79, '79'),
            array(80, 'IT'),
            array(81, 'BHUR'),
            array(82, '82'),
            array(83, '83'),
            array(84, 'BHUR'),
            array(85, 'IT'),
            array(86, '86'),
            array(87, 'BHUR'),
            array(88, '88'),
            array(89, '89'),
            array(90, 'BHUR TI'),
            array(91, '91'),
            array(92, '92'),
            array(93, 'BHUR'),
            array(94, '94'),
            array(95, 'IT'),
            array(96, 'BHUR'),
            array(97, '97'),
            array(98, '98'),
            array(99, 'BHUR'),
            array(100, 'IT')
        );
    }

}

